"""recent changes

Revision ID: 43607d2b8320
Revises: 1a97d2155c65
Create Date: 2023-10-18 15:24:30.700881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43607d2b8320'
down_revision = '1a97d2155c65'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
